# Generated by Django 4.0.3 on 2022-04-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_des', models.CharField(max_length=50)),
                ('book_image', models.ImageField(default=None, max_length='250', null=True, upload_to='book/')),
            ],
        ),
    ]
