# Generated by Django 4.0.3 on 2022-04-11 11:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='book_name', unique=True),
        ),
    ]
